benjali = [("0980","ঀ","BENGALI ANJI"),
("0981","$ঁ","BENGALI SIGN CANDRABINDU"),
("0982","$ং","BENGALI SIGN ANUSVARA"),
("0983","$ঃ","BENGALI SIGN VISARGA"),
("0985","অ","BENGALI LETTER A"),
("0986","আ","BENGALI LETTER AA"),
("0987","ই","BENGALI LETTER I"),
("0988","ঈ","BENGALI LETTER II"),
("0989","উ","BENGALI LETTER U"),
("098A","ঊ","BENGALI LETTER UU"),
("098B","ঋ","BENGALI LETTER VOCALIC R"),
("098C","ঌ","BENGALI LETTER VOCALIC L"),
("098F","এ","BENGALI LETTER E"),
("0990","ঐ","BENGALI LETTER AI"),
("0993","ও","BENGALI LETTER O"),
("0994","ঔ","BENGALI LETTER AU"),
("0995","ক","BENGALI LETTER KA"),
("0996","খ","BENGALI LETTER KHA"),
("0997","গ","BENGALI LETTER GA"),
("0998","ঘ","BENGALI LETTER GHA"),
("0999","ঙ","BENGALI LETTER NGA"),
("099A","চ","BENGALI LETTER CA"),
("099B","ছ","BENGALI LETTER CHA"),
("099C","জ","BENGALI LETTER JA"),
("099D","ঝ","BENGALI LETTER JHA"),
("099E","ঞ","BENGALI LETTER NYA"),
("099F","ট","BENGALI LETTER TTA"),
("09A0","ঠ","BENGALI LETTER TTHA"),
("09A1","ড","BENGALI LETTER DDA"),
("09A2","ঢ","BENGALI LETTER DDHA"),
("09A3","ণ","BENGALI LETTER NNA"),
("09A4","ত","BENGALI LETTER TA"),
("09A5","থ","BENGALI LETTER THA"),
("09A6","দ","BENGALI LETTER DA"),
("09A7","ধ","BENGALI LETTER DHA"),
("09A8","ন","BENGALI LETTER NA"),
("09AA","প","BENGALI LETTER PA"),
("09AB","ফ","BENGALI LETTER PHA"),
("09AC","ব","BENGALI LETTER BA"),
("09AD","ভ","BENGALI LETTER BHA"),
("09AE","ম","BENGALI LETTER MA"),
("09AF","য","BENGALI LETTER YA"),
("09B0","র","BENGALI LETTER RA"),
("09B2","ল","BENGALI LETTER LA"),
("09B6","শ","BENGALI LETTER SHA"),
("09B7","ষ","BENGALI LETTER SSA"),
("09B8","স","BENGALI LETTER SA"),
("09B9","হ","BENGALI LETTER HA"),
("09BC","$়","BENGALI SIGN NUKTA"),
("09BD","ঽ","BENGALI SIGN AVAGRAHA"),
("09BE","$া","BENGALI VOWEL SIGN AA"),
("09BF","$ি","BENGALI VOWEL SIGN I"),
("09C0","$ী","BENGALI VOWEL SIGN II"),
("09C1","$ু","BENGALI VOWEL SIGN U"),
("09C2","$ূ","BENGALI VOWEL SIGN UU"),
("09C3","$ৃ","BENGALI VOWEL SIGN VOCALIC R"),
("09C4","$ৄ","BENGALI VOWEL SIGN VOCALIC RR"),
("09C7","$ে","BENGALI VOWEL SIGN E"),
("09C8","$ৈ","BENGALI VOWEL SIGN AI"),
("09CB","$ো","BENGALI VOWEL SIGN O"),
("09CC","$ৌ","BENGALI VOWEL SIGN AU"),
("09CD","$্","BENGALI SIGN VIRAMA"),
("09CE","ৎ","BENGALI LETTER KHANDA TA"),
("09D7","$ৗ","BENGALI AU LENGTH MARK"),
("09DC","ড়","BENGALI LETTER RRA"),
("09DD","ঢ়","BENGALI LETTER RHA"),
("09DF","য়","BENGALI LETTER YYA"),
("09E0","ৠ","BENGALI LETTER VOCALIC RR"),
("09E1","ৡ","BENGALI LETTER VOCALIC LL"),
("09E2","$ৢ","BENGALI VOWEL SIGN VOCALIC L"),
("09E3","$ৣ","BENGALI VOWEL SIGN VOCALIC LL"),
("09E6","০","BENGALI DIGIT ZERO"),
("09E7","১","BENGALI DIGIT ONE"),
("09E8","২","BENGALI DIGIT TWO"),
("09E9","৩","BENGALI DIGIT THREE"),
("09EA","৪","BENGALI DIGIT FOUR"),
("09EB","৫","BENGALI DIGIT FIVE"),
("09EC","৬","BENGALI DIGIT SIX"),
("09ED","৭","BENGALI DIGIT SEVEN"),
("09EE","৮","BENGALI DIGIT EIGHT"),
("09EF","৯","BENGALI DIGIT NINE"),
("09F0","ৰ","BENGALI LETTER RA WITH MIDDLE DIAGONAL"),
("09F1","ৱ","BENGALI LETTER RA WITH LOWER DIAGONAL"),
("09F2","৲","BENGALI RUPEE MARK"),
("09F3","৳","BENGALI RUPEE SIGN"),
("09F4","৴","BENGALI CURRENCY NUMERATOR ONE"),
("09F5","৵","BENGALI CURRENCY NUMERATOR TWO"),
("09F6","৶","BENGALI CURRENCY NUMERATOR THREE"),
("09F7","৷","BENGALI CURRENCY NUMERATOR FOUR"),
("09F8","৸","BENGALI CURRENCY NUMERATOR ONE LESS"),
("09F9","৹","BENGALI CURRENCY DENOMINATOR SIXTEEN"),
("09FA","৺","BENGALI ISSHAR"),
("09FB","৻","BENGALI GANDA MARK"),
("09FC","","BENGALI LETTER VEDIC ANUSVARA"),
("09FD","॰","BENGALI ABBREVIATION SIGN"),
("09FE","ঽ","BENGALI SANDHI MARK")]

gujarati = [
("0A81","◌ઁ","Gujarati Sign Candrabindu"),
("0A82","◌ં","Gujarati Sign Anusvara"),
("0A83","ઃ","Gujarati Sign Visarga"),
("0A85","અ","Gujarati Letter A"),
("0A86","આ","Gujarati Letter Aa"),
("0A87","ઇ","Gujarati Letter I"),
("0A88","ઈ","Gujarati Letter Ii"),
("0A89","ઉ","Gujarati Letter U"),
("0A8A","ઊ","Gujarati Letter Uu"),
("0A8B","ઋ","Gujarati Letter Vocalic R"),
("0A8C","ઌ","Gujarati Letter Vocalic L"),
("0A8D","ઍ","Gujarati Vowel Candra E"),
("0A8F","એ","Gujarati Letter E"),
("0A90","ઐ","Gujarati Letter Ai"),
("0A91","ઑ","Gujarati Vowel Candra O"),
("0A93","ઓ","Gujarati Letter O"),
("0A94","ઔ","Gujarati Letter Au"),
("0A95","ક","Gujarati Letter Ka"),
("0A96","ખ","Gujarati Letter Kha"),
("0A97","ગ","Gujarati Letter Ga"),
("0A98","ઘ","Gujarati Letter Gha"),
("0A99","ઙ","Gujarati Letter Nga"),
("0A9A","ચ","Gujarati Letter Ca"),
("0A9B","છ","Gujarati Letter Cha"),
("0A9C","જ","Gujarati Letter Ja"),
("0A9D","ઝ","Gujarati Letter Jha"),
("0A9E","ઞ","Gujarati Letter Nya"),
("0A9F","ટ","Gujarati Letter Tta"),
("0AA0","ઠ","Gujarati Letter Ttha"),
("0AA1","ડ","Gujarati Letter Dda"),
("0AA2","ઢ","Gujarati Letter Ddha"),
("0AA3","ણ","Gujarati Letter Nna"),
("0AA4","ત","Gujarati Letter Ta"),
("0AA5","થ","Gujarati Letter Tha"),
("0AA6","દ","Gujarati Letter Da"),
("0AA7","ધ","Gujarati Letter Dha"),
("0AA8","ન","Gujarati Letter Na"),
("0AAA","પ","Gujarati Letter Pa"),
("0AAB","ફ","Gujarati Letter Pha"),
("0AAC","બ","Gujarati Letter Ba"),
("0AAD","ભ","Gujarati Letter Bha"),
("0AAE","મ","Gujarati Letter Ma"),
("0AAF","ય","Gujarati Letter Ya"),
("0AB0","ર","Gujarati Letter Ra"),
("0AB2","લ","Gujarati Letter La"),
("0AB3","ળ","Gujarati Letter Lla"),
("0AB5","વ","Gujarati Letter Va"),
("0AB6","શ","Gujarati Letter Sha"),
("0AB7","ષ","Gujarati Letter Ssa"),
("0AB8","સ","Gujarati Letter Sa"),
("0AB9","હ","Gujarati Letter Ha"),
("0ABC","◌઼","Gujarati Sign Nukta"),
("0ABD","ઽ","Gujarati Sign Avagraha"),
("0ABE","ા","Gujarati Vowel Sign Aa"),
("0ABF","િ","Gujarati Vowel Sign I"),
("0AC0","ી","Gujarati Vowel Sign Ii"),
("0AC1","◌ુ","Gujarati Vowel Sign U"),
("0AC2","◌ૂ","Gujarati Vowel Sign Uu"),
("0AC3","◌ૃ","Gujarati Vowel Sign Vocalic R"),
("0AC4","◌ૄ","Gujarati Vowel Sign Vocalic Rr"),
("0AC5","◌ૅ","Gujarati Vowel Sign Candra E"),
("0AC7","◌ે","Gujarati Vowel Sign E"),
("0AC8","◌ૈ","Gujarati Vowel Sign Ai"),
("0AC9","ૉ","Gujarati Vowel Sign Candra O"),
("0ACB","ો","Gujarati Vowel Sign O"),
("0ACC","ૌ","Gujarati Vowel Sign Au"),
("0ACD","◌્","Gujarati Sign Virama"),
("0AD0","ૐ","Gujarati Om"),
("0AE0","ૠ","Gujarati Letter Vocalic Rr"),
("0AE1","ૡ","Gujarati Letter Vocalic Ll"),
("0AE2","◌ૢ","Gujarati Vowel Sign Vocalic L"),
("0AE3","◌ૣ","Gujarati Vowel Sign Vocalic Ll"),
("0AE6","૦","Gujarati Digit Zero"),
("0AE7","૧","Gujarati Digit One"),
("0AE8","૨","Gujarati Digit Two"),
("0AE9","૩","Gujarati Digit Three"),
("0AEA","૪","Gujarati Digit Four"),
("0AEB","૫","Gujarati Digit Five"),
("0AEC","૬","Gujarati Digit Six"),
("0AED","૭","Gujarati Digit Seven"),
("0AEE","૮","Gujarati Digit Eight"),
("0AEF","૯","Gujarati Digit Nine"),
("0AF0","૰","Gujarati Abbreviation Sign"),
("0AF1","૱","Gujarati Rupee Sign"),
("0AF9","ૹ","Gujarati Letter Zha"),
("0AFA","◌ૺ","Gujarati Sign Sukun"),
("0AFB","◌ૻ","Gujarati Sign Shadda"),
("0AFC","◌ૼ","Gujarati Sign Maddah"),
("0AFD","◌૽","Gujarati Sign Three-Dot Nukta Above"),
("0AFE","◌૾","Gujarati Sign Circle Nukta Above"),
("0AFF","◌૿","Gujarati Sign Two-Circle Nukta Above")]

gurumukhi = [
("0A01"," ਁ", "Gurmukhi Sign Adak Bindi"),
("0A02"," ਂ", "Gurmukhi Sign Bindi"),
("0A03"," ਃ", "Gurmukhi Sign Visarga"),
("0A05", "ਅ", "Gurmukhi Letter A"),
("0A06", "ਆ", "Gurmukhi Letter Aa"),
("0A07", "ਇ", "Gurmukhi Letter I"),
("0A08", "ਈ", "Gurmukhi Letter Ii"),
("0A09", "ਉ", "Gurmukhi Letter U"),
("0A0A", "ਊ", "Gurmukhi Letter Uu"),
("0A0F", "ਏ", "Gurmukhi Letter Ee"),
("0A10", "ਐ", "Gurmukhi Letter Ai"),
("0A13", "ਓ", "Gurmukhi Letter Oo"),
("0A14", "ਔ", "Gurmukhi Letter Au"),
("0A15", "ਕ", "Gurmukhi Letter Ka"),
("0A16", "ਖ", "Gurmukhi Letter Kha"),
("0A17", "ਗ", "Gurmukhi Letter Ga"),
("0A18", "ਘ", "Gurmukhi Letter Gha"),
("0A19", "ਙ", "Gurmukhi Letter Nga"),
("0A1A", "ਚ", "Gurmukhi Letter Ca"),
("0A1B", "ਛ", "Gurmukhi Letter Cha"),
("0A1C", "ਜ", "Gurmukhi Letter Ja"),
("0A1D", "ਝ", "Gurmukhi Letter Jha"),
("0A1E", "ਞ", "Gurmukhi Letter Nya"),
("0A1F", "ਟ", "Gurmukhi Letter Tta"),
("0A20", "ਠ", "Gurmukhi Letter Ttha"),
("0A21", "ਡ", "Gurmukhi Letter Dda"),
("0A22", "ਢ", "Gurmukhi Letter Ddha"),
("0A23", "ਣ", "Gurmukhi Letter Nna"),
("0A24", "ਤ", "Gurmukhi Letter Ta"),
("0A25", "ਥ", "Gurmukhi Letter Tha"),
("0A26", "ਦ", "Gurmukhi Letter Da"),
("0A27", "ਧ", "Gurmukhi Letter Dha"),
("0A28", "ਨ", "Gurmukhi Letter Na"),
("0A2A", "ਪ", "Gurmukhi Letter Pa"),
("0A2B", "ਫ", "Gurmukhi Letter Pha"),
("0A2C", "ਬ", "Gurmukhi Letter Ba"),
("0A2D", "ਭ", "Gurmukhi Letter Bha"),
("0A2E", "ਮ", "Gurmukhi Letter Ma"),
("0A2F", "ਯ", "Gurmukhi Letter Ya"),
("0A30", "ਰ", "Gurmukhi Letter Ra"),
("0A32", "ਲ", "Gurmukhi Letter La"),
("0A33", "ਲ਼", "Gurmukhi Letter Lla"),
("0A35", "ਵ", "Gurmukhi Letter Va"),
("0A36", "ਸ਼", "Gurmukhi Letter Sha"),
("0A38", "ਸ", "Gurmukhi Letter Sa"),
("0A39", "ਹ", "Gurmukhi Letter Ha"),
("0A3C"," ਼", "Gurmukhi Sign Nukta"),
("0A3E"," ਾ", "Gurmukhi Vowel Sign Aa"),
("0A3F"," ਿ", "Gurmukhi Vowel Sign I"),
("0A40"," ੀ", "Gurmukhi Vowel Sign Ii"),
("0A41"," ੁ", "Gurmukhi Vowel Sign U"),
("0A42"," ੂ", "Gurmukhi Vowel Sign Uu"),
("0A47"," ੇ", "Gurmukhi Vowel Sign Ee"),
("0A48"," ੈ", "Gurmukhi Vowel Sign Ai"),
("0A4B"," ੋ", "Gurmukhi Vowel Sign Oo"),
("0A4C"," ੌ", "Gurmukhi Vowel Sign Au"),
("0A4D"," ੍", "Gurmukhi Sign Virama"),
("0A51"," ੑ", "Gurmukhi Sign Udaat"),
("0A59", "ਖ਼", "Gurmukhi Letter Khha"),
("0A5A", "ਗ਼", "Gurmukhi Letter Ghha"),
("0A5B", "ਜ਼", "Gurmukhi Letter Za"),
("0A5C", "ੜ", "Gurmukhi Letter Rra"),
("0A5E", "ਫ਼", "Gurmukhi Letter Fa"),
("0A66", "੦", "Gurmukhi Digit Zero"),
("0A67", "੧", "Gurmukhi Digit One"),
("0A68", "੨", "Gurmukhi Digit Two"),
("0A69", "੩", "Gurmukhi Digit Three"),
("0A6A", "੪", "Gurmukhi Digit Four"),
("0A6B", "੫", "Gurmukhi Digit Five"),
("0A6C", "੬", "Gurmukhi Digit Six"),
("0A6D", "੭", "Gurmukhi Digit Seven"),
("0A6E", "੮", "Gurmukhi Digit Eight"),
("0A6F", "੯", "Gurmukhi Digit Nine"),
("0A70"," ੰ", "Gurmukhi Tippi"),
("0A71"," ੱ", "Gurmukhi Addak"),
("0A72", "ੲ", "Gurmukhi Iri"),
("0A73", "ੳ", "Gurmukhi Ura"),
("0A74", "ੴ", "Gurmukhi Ek Onkar"),
("0A75"," ੵ", "Gurmukhi Sign Yakash"),
("0A76", "੶", "Gurmukhi Abbreviation Sign")]

kannada = [
("0C80","ಀ","Kannada Sign Spacing Candrabindu"),
("0C81","ಁ","Kannada Sign Candrabindu"),
("0C82","ಂ","Kannada Sign Anusvara"),
("0C83","ಃ","Kannada Sign Visarga"),
("0C84","಄","Kannada Sign Siddham"),
("0C85","ಅ","Kannada Letter A"),
("0C86","ಆ","Kannada Letter Aa"),
("0C87","ಇ","Kannada Letter I"),
("0C88","ಈ","Kannada Letter Ii"),
("0C89","ಉ","Kannada Letter U"),
("0C8A","ಊ","Kannada Letter Uu"),
("0C8B","ಋ","Kannada Letter Vocalic R"),
("0C8C","ಌ","Kannada Letter Vocalic L"),
("0C8E","ಎ","Kannada Letter E"),
("0C8F","ಏ","Kannada Letter Ee"),
("0C90","ಐ","Kannada Letter Ai"),
("0C92","ಒ","Kannada Letter O"),
("0C93","ಓ","Kannada Letter Oo"),
("0C94","ಔ","Kannada Letter Au"),
("0C95","ಕ","Kannada Letter Ka"),
("0C96","ಖ","Kannada Letter Kha"),
("0C97","ಗ","Kannada Letter Ga"),
("0C98","ಘ","Kannada Letter Gha"),
("0C99","ಙ","Kannada Letter Nga"),
("0C9A","ಚ","Kannada Letter Ca"),
("0C9B","ಛ","Kannada Letter Cha"),
("0C9C","ಜ","Kannada Letter Ja"),
("0C9D","ಝ","Kannada Letter Jha"),
("0C9E","ಞ","Kannada Letter Nya"),
("0C9F","ಟ","Kannada Letter Tta"),
("0CA0","ಠ","Kannada Letter Ttha"),
("0CA1","ಡ","Kannada Letter Dda"),
("0CA2","ಢ","Kannada Letter Ddha"),
("0CA3","ಣ","Kannada Letter Nna"),
("0CA4","ತ","Kannada Letter Ta"),
("0CA5","ಥ","Kannada Letter Tha"),
("0CA6","ದ","Kannada Letter Da"),
("0CA7","ಧ","Kannada Letter Dha"),
("0CA8","ನ","Kannada Letter Na"),
("0CAA","ಪ","Kannada Letter Pa"),
("0CAB","ಫ","Kannada Letter Pha"),
("0CAC","ಬ","Kannada Letter Ba"),
("0CAD","ಭ","Kannada Letter Bha"),
("0CAE","ಮ","Kannada Letter Ma"),
("0CAF","ಯ","Kannada Letter Ya"),
("0CB0","ರ","Kannada Letter Ra"),
("0CB1","ಱ","Kannada Letter Rra"),
("0CB2","ಲ","Kannada Letter La"),
("0CB3","ಳ","Kannada Letter Lla"),
("0CB5","ವ","Kannada Letter Va"),
("0CB6","ಶ","Kannada Letter Sha"),
("0CB7","ಷ","Kannada Letter Ssa"),
("0CB8","ಸ","Kannada Letter Sa"),
("0CB9","ಹ","Kannada Letter Ha")]

malayalam =[
("0D00","ഀ","Malayalam Sign Combining Anusvara Above"),
("0D01","ഁ","Malayalam Sign Candrabindu"),
("0D02","ം","Malayalam Sign Anusvara"),
("0D03","ഃ","Malayalam Sign Visarga"),
("0D04","ഄ","Malayalam Letter Vedic Anusvara"),
("0D05","അ","Malayalam Letter A"),
("0D06","ആ","Malayalam Letter Aa"),
("0D07","ഇ","Malayalam Letter I"),
("0D08","ഈ","Malayalam Letter Ii"),
("0D09","ഉ","Malayalam Letter U"),
("0D0A","ഊ","Malayalam Letter Uu"),
("0D0B","ഋ","Malayalam Letter Vocalic R"),
("0D0C","ഌ","Malayalam Letter Vocalic L"),
("0D0E","എ","Malayalam Letter E"),
("0D0F","ഏ","Malayalam Letter Ee"),
("0D10","ഐ","Malayalam Letter Ai"),
("0D12","ഒ","Malayalam Letter O"),
("0D13","ഓ","Malayalam Letter Oo"),
("0D14","ഔ","Malayalam Letter Au"),
("0D15","ക","Malayalam Letter Ka"),
("0D16","ഖ","Malayalam Letter Kha"),
("0D17","ഗ","Malayalam Letter Ga"),
("0D18","ഘ","Malayalam Letter Gha"),
("0D19","ങ","Malayalam Letter Nga"),
("0D1A","ച","Malayalam Letter Ca"),
("0D1B","ഛ","Malayalam Letter Cha"),
("0D1C","ജ","Malayalam Letter Ja"),
("0D1D","ഝ","Malayalam Letter Jha"),
("0D1E","ഞ","Malayalam Letter Nya"),
("0D1F","ട","Malayalam Letter Tta"),
("0D20","ഠ","Malayalam Letter Ttha"),
("0D21","ഡ","Malayalam Letter Dda"),
("0D22","ഢ","Malayalam Letter Ddha"),
("0D23","ണ","Malayalam Letter Nna"),
("0D24","ത","Malayalam Letter Ta"),
("0D25","ഥ","Malayalam Letter Tha"),
("0D26","ദ","Malayalam Letter Da"),
("0D27","ധ","Malayalam Letter Dha"),
("0D28","ന","Malayalam Letter Na"),
("0D29","ഩ","Malayalam Letter Nnna"),
("0D2A","പ","Malayalam Letter Pa"),
("0D2B","ഫ","Malayalam Letter Pha"),
("0D2C","ബ","Malayalam Letter Ba"),
("0D2D","ഭ","Malayalam Letter Bha"),
("0D2E","മ","Malayalam Letter Ma"),
("0D2F","യ","Malayalam Letter Ya"),
("0D30","ര","Malayalam Letter Ra"),
("0D31","റ","Malayalam Letter Rra"),
("0D32","ല","Malayalam Letter La"),
("0D33","ള","Malayalam Letter Lla"),
("0D34","ഴ","Malayalam Letter Llla"),
("0D35","വ","Malayalam Letter Va"),
("0D36","ശ","Malayalam Letter Sha"),
("0D37","ഷ","Malayalam Letter Ssa"),
("0D38","സ","Malayalam Letter Sa"),
("0D39","ഹ","Malayalam Letter Ha"),
("0D3A","ഺ","Malayalam Letter Ttta"),
("0D3B","഻","Malayalam Sign Vertical Bar Virama"),
("0D3C","഼","Malayalam Sign Circular Virama"),
("0D3D","ഽ","Malayalam Sign Avagraha"),
("0D3E","ാ","Malayalam Vowel Sign Aa"),
("0D3F","ി","Malayalam Vowel Sign I"),
("0D40","ീ","Malayalam Vowel Sign Ii"),
("0D41","ു","Malayalam Vowel Sign U"),
("0D42","ൂ","Malayalam Vowel Sign Uu"),
("0D43","ൃ","Malayalam Vowel Sign Vocalic R"),
("0D44","ൄ","Malayalam Vowel Sign Vocalic Rr"),
("0D46","െ","Malayalam Vowel Sign E"),
("0D47","േ","Malayalam Vowel Sign Ee"),
("0D48","ൈ","Malayalam Vowel Sign Ai"),
("0D4A","ൊ","Malayalam Vowel Sign O"),
("0D4B","ോ","Malayalam Vowel Sign Oo"),
("0D4C","ൌ","Malayalam Vowel Sign Au"),
("0D4D","്","Malayalam Sign Virama"),
("0D4E","ൎ","Malayalam Letter Dot Reph"),
("0D4F","൏","Malayalam Sign Para"),
("0D54","ൔ","Malayalam Letter Chillu M"),
("0D55","ൕ","Malayalam Letter Chillu Y"),
("0D56","ൖ","Malayalam Letter Chillu Lll"),
("0D57","ൗ","Malayalam Au Length Mark"),
("0D58","൘","Malayalam Fraction One One-Hundred-and-Sixtieth"),
("0D59","൙","Malayalam Fraction One Fortieth"),
("0D5A","൚","Malayalam Fraction Three Eightieths"),
("0D5B","൛","Malayalam Fraction One Twentieth"),
("0D5C","൜","Malayalam Fraction One Tenth"),
("0D5D","൝","Malayalam Fraction Three Twentieths"),
("0D5E","൞","Malayalam Fraction One Fifth"),
("0D5F","ൟ","Malayalam Letter Archaic Ii"),
("0D60","ൠ","Malayalam Letter Vocalic Rr"),
("0D61","ൡ","Malayalam Letter Vocalic Ll"),
("0D62","ൢ","Malayalam Vowel Sign Vocalic L"),
("0D63","ൣ","Malayalam Vowel Sign Vocalic Ll"),
("0D66","൦","Malayalam Digit Zero"),
("0D67","൧","Malayalam Digit One"),
("0D68","൨","Malayalam Digit Two"),
("0D69","൩","Malayalam Digit Three"),
("0D6A","൪","Malayalam Digit Four"),
("0D6B","൫","Malayalam Digit Five"),
("0D6C","൬","Malayalam Digit Six"),
("0D6D","൭","Malayalam Digit Seven"),
("0D6E","൮","Malayalam Digit Eight"),
("0D6F","൯","Malayalam Digit Nine"),
("0D70","൰","Malayalam Number Ten"),
("0D71","൱","Malayalam Number One Hundred"),
("0D72","൲","Malayalam Number One Thousand"),
("0D73","൳","Malayalam Fraction One Quarter"),
("0D74","൴","Malayalam Fraction One Half"),
("0D75","൵","Malayalam Fraction Three Quarters"),
("0D76","൶","Malayalam Fraction One Sixteenth"),
("0D77","൷","Malayalam Fraction One Eighth"),
("0D78","൸","Malayalam Fraction Three Sixteenths"),
("0D79","൹","Malayalam Date Mark"),
("0D7A","ൺ","Malayalam Letter Chillu Nn"),
("0D7B","ൻ","Malayalam Letter Chillu N"),
("0D7C","ർ","Malayalam Letter Chillu Rr"),
("0D7D","ൽ","Malayalam Letter Chillu L"),
("0D7E","ൾ","Malayalam Letter Chillu Ll"),
("0D7F","ൿ","Malayalam Letter Chillu K")]

telugu = [
("0C00","ఀ","Telugu Sign Combining Candrabindu Above"),
("0C01","ఁ","Telugu Sign Candrabindu"),
("0C02","ం","Telugu Sign Anusvara"),
("0C03","ః","Telugu Sign Visarga"),
("0C04","ఄ","Telugu Sign Combining Anusvara Above"),
("0C05","అ","Telugu Letter A"),
("0C06","ఆ","Telugu Letter Aa"),
("0C07","ఇ","Telugu Letter I"),
("0C08","ఈ","Telugu Letter Ii"),
("0C09","ఉ","Telugu Letter U"),
("0C0A","ఊ","Telugu Letter Uu"),
("0C0B","ఋ","Telugu Letter Vocalic R"),
("0C0C","ఌ","Telugu Letter Vocalic L"),
("0C0E","ఎ","Telugu Letter E"),
("0C0F","ఏ","Telugu Letter Ee"),
("0C10","ఐ","Telugu Letter Ai"),
("0C12","ఒ","Telugu Letter O"),
("0C13","ఓ","Telugu Letter Oo"),
("0C14","ఔ","Telugu Letter Au"),
("0C15","క","Telugu Letter Ka"),
("0C16","ఖ","Telugu Letter Kha"),
("0C17","గ","Telugu Letter Ga"),
("0C18","ఘ","Telugu Letter Gha"),
("0C19","ఙ","Telugu Letter Nga"),
("0C1A","చ","Telugu Letter Ca"),
("0C1B","ఛ","Telugu Letter Cha"),
("0C1C","జ","Telugu Letter Ja"),
("0C1D","ఝ","Telugu Letter Jha"),
("0C1E","ఞ","Telugu Letter Nya"),
("0C1F","ట","Telugu Letter Tta"),
("0C20","ఠ","Telugu Letter Ttha"),
("0C21","డ","Telugu Letter Dda"),
("0C22","ఢ","Telugu Letter Ddha"),
("0C23","ణ","Telugu Letter Nna"),
("0C24","త","Telugu Letter Ta"),
("0C25","థ","Telugu Letter Tha"),
("0C26","ద","Telugu Letter Da"),
("0C27","ధ","Telugu Letter Dha"),
("0C28","న","Telugu Letter Na"),
("0C2A","ప","Telugu Letter Pa"),
("0C2B","ఫ","Telugu Letter Pha"),
("0C2C","బ","Telugu Letter Ba"),
("0C2D","భ","Telugu Letter Bha"),
("0C2E","మ","Telugu Letter Ma"),
("0C2F","య","Telugu Letter Ya"),
("0C30","ర","Telugu Letter Ra"),
("0C31","ఱ","Telugu Letter Rra"),
("0C32","ల","Telugu Letter La"),
("0C33","ళ","Telugu Letter Lla"),
("0C34","ఴ","Telugu Letter Llla"),
("0C35","వ","Telugu Letter Va"),
("0C36","శ","Telugu Letter Sha"),
("0C37","ష","Telugu Letter Ssa"),
("0C38","స","Telugu Letter Sa"),
("0C39","హ","Telugu Letter Ha"),
("0C3C","఼","Telugu Sign Nukta"),
("0C3D","ఽ","Telugu Sign Avagraha"),
("0C3E","ా","Telugu Vowel Sign Aa"),
("0C3F","ి","Telugu Vowel Sign I"),
("0C40","ీ","Telugu Vowel Sign Ii"),
("0C41","ు","Telugu Vowel Sign U"),
("0C42","ూ","Telugu Vowel Sign Uu"),
("0C43","ృ","Telugu Vowel Sign Vocalic R"),
("0C44","ౄ","Telugu Vowel Sign Vocalic Rr"),
("0C46","ె","Telugu Vowel Sign E"),
("0C47","ే","Telugu Vowel Sign Ee"),
("0C48","ై","Telugu Vowel Sign Ai"),
("0C4A","ొ","Telugu Vowel Sign O"),
("0C4B","ో","Telugu Vowel Sign Oo"),
("0C4C","ౌ","Telugu Vowel Sign Au"),
("0C4D","్","Telugu Sign Virama"),
("0C55","ౕ","Telugu Length Mark"),
("0C56","ౖ","Telugu Ai Length Mark"),
("0C58","ౘ","Telugu Letter Tsa"),
("0C59","ౙ","Telugu Letter Dza"),
("0C5A","ౚ","Telugu Letter Rrra"),
("0C5D","ౝ","Telugu Letter Nakaara Pollu"),
("0C60","ౠ","Telugu Letter Vocalic Rr"),
("0C61","ౡ","Telugu Letter Vocalic Ll"),
("0C62","ౢ","Telugu Vowel Sign Vocalic L"),
("0C63","ౣ","Telugu Vowel Sign Vocalic Ll"),
("0C66","౦","Telugu Digit Zero"),
("0C67","౧","Telugu Digit One"),
("0C68","౨","Telugu Digit Two"),
("0C69","౩","Telugu Digit Three"),
("0C6A","౪","Telugu Digit Four"),
("0C6B","౫","Telugu Digit Five"),
("0C6C","౬","Telugu Digit Six"),
("0C6D","౭","Telugu Digit Seven"),
("0C6E","౮","Telugu Digit Eight"),
("0C6F","౯","Telugu Digit Nine"),
("0C77","౷","Telugu Sign Siddham"),
("0C78","౸","Telugu Fraction Digit Zero for Odd Powers of Four"),
("0C79","౹","Telugu Fraction Digit One for Odd Powers of Four"),
("0C7A","౺","Telugu Fraction Digit Two for Odd Powers of Four"),
("0C7B","౻","Telugu Fraction Digit Three for Odd Powers of Four"),
("0C7C","౼","Telugu Fraction Digit One for Even Powers of Four"),
("0C7D","౽","Telugu Fraction Digit Two for Even Powers of Four"),
("0C7E","౾","Telugu Fraction Digit Three for Even Powers of Four"),
("0C7F","౿","Telugu Sign Tuumu")]

oriya = [
("0B01","ଁ","Oriya Sign Candrabindu"),
("0B02","ଂ","Oriya Sign Anusvara"),
("0B03","ଃ","Oriya Sign Visarga"),
("0B05","ଅ","Oriya Letter A"),
("0B06","ଆ","Oriya Letter Aa"),
("0B07","ଇ","Oriya Letter I"),
("0B08","ଈ","Oriya Letter Ii"),
("0B09","ଉ","Oriya Letter U"),
("0B0A","ଊ","Oriya Letter Uu"),
("0B0B","ଋ","Oriya Letter Vocalic R"),
("0B0C","ଌ","Oriya Letter Vocalic L"),
("0B0F","ଏ","Oriya Letter E"),
("0B10","ଐ","Oriya Letter Ai"),
("0B13","ଓ","Oriya Letter O"),
("0B14","ଔ","Oriya Letter Au"),
("0B15","କ","Oriya Letter Ka"),
("0B16","ଖ","Oriya Letter Kha"),
("0B17","ଗ","Oriya Letter Ga"),
("0B18","ଘ","Oriya Letter Gha"),
("0B19","ଙ","Oriya Letter Nga"),
("0B1A","ଚ","Oriya Letter Ca"),
("0B1B","ଛ","Oriya Letter Cha"),
("0B1C","ଜ","Oriya Letter Ja"),
("0B1D","ଝ","Oriya Letter Jha"),
("0B1E","ଞ","Oriya Letter Nya"),
("0B1F","ଟ","Oriya Letter Tta"),
("0B20","ଠ","Oriya Letter Ttha"),
("0B21","ଡ","Oriya Letter Dda"),
("0B22","ଢ","Oriya Letter Ddha"),
("0B23","ଣ","Oriya Letter Nna"),
("0B24","ତ","Oriya Letter Ta"),
("0B25","ଥ","Oriya Letter Tha"),
("0B26","ଦ","Oriya Letter Da"),
("0B27","ଧ","Oriya Letter Dha"),
("0B28","ନ","Oriya Letter Na"),
("0B2A","ପ","Oriya Letter Pa"),
("0B2B","ଫ","Oriya Letter Pha"),
("0B2C","ବ","Oriya Letter Ba"),
("0B2D","ଭ","Oriya Letter Bha"),
("0B2E","ମ","Oriya Letter Ma"),
("0B2F","ଯ","Oriya Letter Ya"),
("0B30","ର","Oriya Letter Ra"),
("0B32","ଲ","Oriya Letter La"),
("0B33","ଳ","Oriya Letter Lla"),
("0B35","ଵ","Oriya Letter Va"),
("0B36","ଶ","Oriya Letter Sha"),
("0B37","ଷ","Oriya Letter Ssa"),
("0B38","ସ","Oriya Letter Sa"),
("0B39","ହ","Oriya Letter Ha"),
("0B3C","଼","Oriya Sign Nukta"),
("0B3D","ଽ","Oriya Sign Avagraha"),
("0B3E","ା","Oriya Vowel Sign Aa"),
("0B3F","ି","Oriya Vowel Sign I"),
("0B40","ୀ","Oriya Vowel Sign Ii"),
("0B41","ୁ","Oriya Vowel Sign U"),
("0B42","ୂ","Oriya Vowel Sign Uu"),
("0B43","ୃ","Oriya Vowel Sign Vocalic R"),
("0B44","ୄ","Oriya Vowel Sign Vocalic Rr"),
("0B47","େ","Oriya Vowel Sign E"),
("0B48","ୈ","Oriya Vowel Sign Ai"),
("0B4B","ୋ","Oriya Vowel Sign O"),
("0B4C","ୌ","Oriya Vowel Sign Au"),
("0B4D","୍","Oriya Sign Virama"),
("0B55","୕","Oriya Sign Overline"),
("0B56","ୖ","Oriya Ai Length Mark"),
("0B57","ୗ","Oriya Au Length Mark"),
("0B5C","ଡ଼","Oriya Letter Rra"),
("0B5D","ଢ଼","Oriya Letter Rha"),
("0B5F","ୟ","Oriya Letter Yya"),
("0B60","ୠ","Oriya Letter Vocalic Rr"),
("0B61","ୡ","Oriya Letter Vocalic Ll"),
("0B62","ୢ","Oriya Vowel Sign Vocalic L"),
("0B63","ୣ","Oriya Vowel Sign Vocalic Ll"),
("0B66","୦","Oriya Digit Zero"),
("0B67","୧","Oriya Digit One"),
("0B68","୨","Oriya Digit Two"),
("0B69","୩","Oriya Digit Three"),
("0B6A","୪","Oriya Digit Four"),
("0B6B","୫","Oriya Digit Five"),
("0B6C","୬","Oriya Digit Six"),
("0B6D","୭","Oriya Digit Seven"),
("0B6E","୮","Oriya Digit Eight"),
("0B6F","୯","Oriya Digit Nine"),
("0B70","୰","Oriya Isshar"),
("0B71","ୱ","Oriya Letter Wa"),
("0B72","୲","Oriya Fraction One Quarter"),
("0B73","୳","Oriya Fraction One Half"),
("0B74","୴","Oriya Fraction Three Quarters"),
("0B75","୵","Oriya Fraction One Sixteenth"),
("0B76","୶","Oriya Fraction One Eighth"),
("0B77","୷","Oriya Fraction Three Sixteenths")]

def get_vocab(lang):
    chars = [chr(int(i[0],16)) for i in lang]
    return "".join(chars) +"\n"

if __name__ == "__main__":
    with open("vocab.txt","w",encoding="utf-8") as f:
        f.write("benjali " + get_vocab(benjali))
        f.write("gujarati " + get_vocab(gujarati))
        f.write("gurumukhi " + get_vocab(gurumukhi))
        f.write("kannada " + get_vocab(kannada))
        f.write("malayalam " + get_vocab(malayalam))
        f.write("telugu " + get_vocab(telugu))
        f.write("oriya " + get_vocab(oriya))